# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "hashicrop/precise32"
  config.vm.hostname="web-developer"
  
  config.vm.provision "shell", path: "provision.sh"
end
